White-Whale-Defi-Platform/migaloo-chain

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/1_bug.md
- .github/ISSUE_TEMPLATE/2_improvement.md
- .github/ISSUE_TEMPLATE/3_feature_request.md
- .github/ISSUE_TEMPLATE/4_infrastructure.md
- .github/ISSUE_TEMPLATE/config.yml
- README.md
- docs/CONTRIBUTING.md
- docs/SECURITY.md
Improvements to the docs, i.e. adding links, new code owners and more.
---
> docs: various docs improvements

- networks/planning/genesis.json
Add multisig account for testnet
---
> add multisig account

- README.md
> Go report card

- app/app_test.go
> Test: blocked module account addresses

- go.mod
- go.sum
This PR updates to the latest upstream version of alliance.
---
> use alliance v0.0.1-beta4

- networks/testnet/README.md
Adding the initial skeleton instruction for testnet gentx
> add testnet gentx instruction with empty gentx folder

- networks/testnet/pre-genesis.json
Adds the correct testnet pre-genesis file
---
> fix(testnet): add valid genesis

- networks/testnet/gentx/gentx-123e2d64c308bcd260dd579d343aec511f09727c.json
> polkachu gentx

- go.mod
- go.sum
> use skip by default

- app/app_test.go
- app/sim_test.go
#21 
I checked the tests and found that there should be test for case Simulation After Import like in sdk simapp
> Add test case

- app/ante.go
- app/app.go
- app/test_helpers.go
- cmd/migalood/root.go
> lint and Adapt wrapped errors to sdk 46 style

- app/app.go
- scripts/testnode.sh
Add ICA app module to module.NewManager
Related #https://github.com/White-Whale-Defi-Platform/migaloo-chain/pull/65
@pysel 
---
> Add ICA app module to module.NewManager

- app/params/config.go
- cmd/migalood/cmd/root.go
- cmd/migalood/main.go
> fix : break keyring 

- Makefile
> Fix whitespace for Make 4.3

- app/app.go
Duplicated initialization of the IBCFeeKeeper. 
https://github.com/White-Whale-Defi-Platform/migaloo-chain/issues/107
---
> Removed duplicated IBCFeeKeeper

- app/app.go
- app/upgrades/v2/upgrades.go
- Add RunMigrate
- Add store migrate
---
> Fix upgrade handler for v2.0.0

- app/ante.go
- app/app.go
- app/params/config.go
> add globalfee to ante handler

- .golangci.yml
- app/app.go
Package forward middleware was not add to transfer stack in ibc router
---
> add pfm to transfer stack

- app/app.go
- app/upgrades/v2_2_5/constants.go
- app/upgrades/v2_2_5/upgrades.go
> Fix upgrade handler in v2.2.5

- app/app.go
add PFM SetTransferKeeper 
---
> set transfer keeper for pfm

- go.mod
- go.sum
bump version wasmd to hot fix bugs 
https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2023-004.md
---
> bump version wasmd to hot fix bugs
